[project]
name = "agent-devtools"
version = "0.1.0"
description = "One and the best tool to improve agent's performance"
authors = [
    { name = "Roy Dong", email = "roydong5@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
agent-devtools = "agent_devtools:main"

[project.optional-dependencies]
browser = [
    "playwright>=1.61.0",
]

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
